server:
  port: 8771

spring:
  application:
    name: zimug-server-config  #config server项目名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yiitree/my-dongbb-cloud
          searchPaths: zimug-server-config-repo
          username: 772701414@qq.com
          password: Rui0530_git
  security:
    basic:
      enabled: true  #启用基本认证(默认)
    user:
      name: root   #自定义登录用户名
      password: root  #自定义登录密码
  # rabbitmq
  rabbitmq:
    host: 192.168.1.60
    port: 5672
    username: root
    password: root

# 单独暴露bus-refresh是不生效的（访问结果是405）
management:
  endpoints:
    web:
      exposure:
        include:  "*"
#      exposure:
#        include:  bus-refresh

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://root:root@peer1:8761/eureka/eureka/,http://root:root@peer2:8761/eureka/eureka/,http://root:root@peer3:8761/eureka/eureka/
  instance:
    preferIpAddress: true

